include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    public_member_api_docs: false

analyzer:
  errors:
    invalid_annotation_target: false
    one_member_abstracts: false
    inference_failure_on_instance_creation: false
    inference_failure_on_function_invocation: false
  exclude:
    - "build/**"
    - "**/*.config.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
