name: flutter_social
description: Flutter social app

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_route: ^7.7.0
  bloc: ^8.1.2
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  device_info_plus: ^9.0.2
  dio: ^5.2.1+1
  dio_cache_interceptor: ^3.4.2
  dio_smart_retry: ^5.0.0
  easy_image_viewer: ^1.2.1
  envied: ^0.3.0+3
  equatable: ^2.0.5
  extended_image: ^8.1.1
  external_path: ^1.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_easyloading: ^3.0.5
  flutter_native_image: ^0.0.6+1
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  flutter_vibrate: ^1.3.0
  freezed_annotation: ^2.4.1
  geocoding: ^2.1.0
  geolocator: ^10.1.0
  get_it: ^7.6.0
  graphql_flutter: ^5.2.0-beta.5
  image_picker: ^1.0.4
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.1.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  keyboard_attachable: ^2.1.0
  logger: ^2.0.2+1
  markdown_editor_plus: ^0.2.13
  package_info_plus: ^4.2.0
  path_provider: ^2.0.15
  permission_handler: ^11.0.1
  pull_to_refresh: ^2.0.0
  rate_limiter: ^1.0.0
  reactive_forms: ^16.1.0
  readmore: ^2.2.0
  recase: ^4.1.0
  share_plus: ^7.2.1

  skeletonizer: ^0.8.0
  slang_flutter: ^3.20.0
  timeago: ^3.5.0
  uni_links: ^0.5.1
  url_launcher: ^6.1.12

dev_dependencies:
  auto_route_generator: ^7.1.1
  bloc_test: ^9.1.3
  build_runner: ^2.4.4
  change_app_package_name: ^1.1.0
  envied_generator:
    git:
      url: https://github.com/ryanaidilp/envied.git
      path: packages/envied_generator
  flutter_flavorizr: ^2.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  slang_build_runner: ^3.20.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/illustration/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
    flare_flutter: true
    lottie: true
    rive: false
  line_length: 80

# Flavor configuration
flavorizr:
  development:
    app:
      name: "(Dev) Flutter Social"
      icon: assets/logo/flutter_social_icons.png
    android:
      applicationId: "com.banua_coder.flutter_social"
    ios:
      bundleId: "com.banua_coder.flutter_social"
  production:
    app:
      name: "Flutter Social"
      icon: assets/logo/flutter_social_icons.png
    android:
      applicationId: "com.banua_coder.flutter_social"
    ios:
      bundleId: "com.banua_coder.flutter_social"
